export const INTERNSHIP_JOB_TITLES = {
  technology: [
    "Software Development Intern",
    "Frontend Development Intern", 
    "Backend Development Intern",
    "Full Stack Development Intern",
    "Mobile App Development Intern",
    "Data Science Intern",
    "Machine Learning Intern",
    "AI/ML Engineering Intern",
    "Cybersecurity Intern",
    "DevOps Engineering Intern",
    "Cloud Engineering Intern",
    "Blockchain Development Intern",
    "Game Development Intern",
    "UI/UX Design Intern",
    "Product Design Intern",
    "QA Testing Intern",
    "System Administration Intern",
    "Network Engineering Intern",
    "Database Administration Intern",
    "Technical Writing Intern",
    "IT Support Intern",
    "Robotics Engineering Intern",
    "Computer Vision Intern",
    "Natural Language Processing Intern",
    "Software Architecture Intern"
  ],
  business: [
    "Business Analyst Intern",
    "Product Management Intern",
    "Project Management Intern",
    "Operations Intern",
    "Strategy Intern",
    "Consulting Intern",
    "Business Development Intern",
    "Sales Intern",
    "Marketing Intern",
    "Digital Marketing Intern",
    "Social Media Marketing Intern",
    "Content Marketing Intern",
    "SEO/SEM Intern",
    "Brand Management Intern",
    "Market Research Intern",
    "Customer Success Intern",
    "Partnership Development Intern",
    "Venture Capital Intern",
    "Investment Banking Intern",
    "Financial Analysis Intern",
    "Accounting Intern",
    "Audit Intern",
    "Risk Management Intern",
    "Supply Chain Intern",
    "Procurement Intern"
  ],
  design: [
    "Graphic Design Intern",
    "Visual Design Intern",
    "User Experience Design Intern",
    "User Interface Design Intern",
    "Interaction Design Intern",
    "Product Design Intern",
    "Industrial Design Intern",
    "Fashion Design Intern",
    "Interior Design Intern",
    "Architectural Design Intern",
    "Motion Graphics Intern",
    "Video Production Intern",
    "Photography Intern",
    "Creative Direction Intern",
    "Art Direction Intern",
    "Brand Design Intern",
    "Web Design Intern",
    "Game Art Intern",
    "3D Modeling Intern",
    "Animation Intern"
  ],
  media: [
    "Content Creation Intern",
    "Social Media Intern",
    "Digital Marketing Intern",
    "Public Relations Intern",
    "Communications Intern",
    "Journalism Intern",
    "Video Production Intern",
    "Podcast Production Intern",
    "Event Planning Intern",
    "Community Management Intern",
    "Influencer Marketing Intern",
    "Content Strategy Intern",
    "Copywriting Intern",
    "Technical Writing Intern",
    "Grant Writing Intern",
    "Research Intern",
    "Data Analysis Intern"
  ],
  healthcare: [
    "Medical Research Intern",
    "Clinical Research Intern",
    "Public Health Intern",
    "Healthcare Administration Intern",
    "Pharmaceutical Intern",
    "Biotechnology Intern",
    "Health Informatics Intern",
    "Mental Health Intern",
    "Epidemiology Intern",
    "Health Policy Intern",
    "Healthcare Analytics Intern",
    "Medical Device Intern",
    "Healthcare Marketing Intern",
    "Healthcare IT Intern"
  ],
  finance: [
    "Investment Banking Intern",
    "Equity Research Intern",
    "Trading Intern",
    "Risk Management Intern",
    "Financial Planning Intern",
    "Corporate Finance Intern",
    "Mergers & Acquisitions Intern",
    "Private Equity Intern",
    "Venture Capital Intern",
    "Hedge Fund Intern",
    "Insurance Intern",
    "Real Estate Finance Intern",
    "Fintech Intern",
    "Cryptocurrency Intern",
    "Quantitative Analysis Intern",
    "Financial Modeling Intern",
    "Compliance Intern",
    "Audit Intern",
    "Tax Intern"
  ],
  engineering: [
    "Mechanical Engineering Intern",
    "Electrical Engineering Intern",
    "Civil Engineering Intern",
    "Chemical Engineering Intern",
    "Aerospace Engineering Intern",
    "Biomedical Engineering Intern",
    "Environmental Engineering Intern",
    "Industrial Engineering Intern",
    "Materials Engineering Intern",
    "Nuclear Engineering Intern",
    "Petroleum Engineering Intern",
    "Robotics Engineering Intern",
    "Automotive Engineering Intern",
    "Manufacturing Engineering Intern",
    "Quality Engineering Intern",
    "Process Engineering Intern",
    "Structural Engineering Intern",
    "Transportation Engineering Intern",
    "Geotechnical Engineering Intern",
    "Water Resources Engineering Intern"
  ],
  science: [
    "Research Intern",
    "Laboratory Intern",
    "Biology Intern",
    "Chemistry Intern",
    "Physics Intern",
    "Mathematics Intern",
    "Statistics Intern",
    "Environmental Science Intern",
    "Geology Intern",
    "Meteorology Intern",
    "Oceanography Intern",
    "Astronomy Intern",
    "Neuroscience Intern",
    "Psychology Intern",
    "Sociology Intern",
    "Anthropology Intern",
    "Economics Intern",
    "Political Science Intern",
    "International Relations Intern",
    "Public Policy Intern"
  ],
  arts: [
    "Fine Arts Intern",
    "Art History Intern",
    "Museum Intern",
    "Gallery Intern",
    "Theater Intern",
    "Music Intern",
    "Dance Intern",
    "Film Production Intern",
    "Creative Writing Intern",
    "Literature Intern",
    "Philosophy Intern",
    "Linguistics Intern",
    "Cultural Studies Intern",
    "Arts Administration Intern",
    "Event Management Intern",
    "Arts Education Intern",
    "Art Therapy Intern",
    "Curatorial Intern",
    "Exhibition Design Intern",
    "Arts Marketing Intern"
  ],
  law: [
    "Legal Intern",
    "Paralegal Intern",
    "Law Clerk Intern",
    "Corporate Law Intern",
    "Criminal Law Intern",
    "Civil Rights Intern",
    "Environmental Law Intern",
    "Intellectual Property Intern",
    "Immigration Law Intern",
    "Family Law Intern",
    "Tax Law Intern",
    "Real Estate Law Intern",
    "Employment Law Intern",
    "International Law Intern",
    "Constitutional Law Intern",
    "Public Interest Intern",
    "Government Relations Intern",
    "Compliance Intern",
    "Legal Research Intern",
    "Policy Analysis Intern"
  ]
};

export const getRandomJobTitle = (category?: keyof typeof INTERNSHIP_JOB_TITLES): string => {
  if (category && INTERNSHIP_JOB_TITLES[category]) {
    const titles = INTERNSHIP_JOB_TITLES[category];
    return titles[Math.floor(Math.random() * titles.length)];
  }
  
  // Get a random category and then a random title from that category
  const categories = Object.keys(INTERNSHIP_JOB_TITLES) as Array<keyof typeof INTERNSHIP_JOB_TITLES>;
  const randomCategory = categories[Math.floor(Math.random() * categories.length)];
  const titles = INTERNSHIP_JOB_TITLES[randomCategory];
  return titles[Math.floor(Math.random() * titles.length)];
};

export const getJobTitlesByCategory = (category: keyof typeof INTERNSHIP_JOB_TITLES): string[] => {
  return INTERNSHIP_JOB_TITLES[category] || [];
};

export const getAllJobTitles = (): string[] => {
  return Object.values(INTERNSHIP_JOB_TITLES).flat();
};
